version: '2.1'
services:
  app:
    build: app/

  oauth2-proxy:
    build: .
    command: >
      '--http-address=0.0.0.0:4180'
      '--cookie-secure=true'
      '--cookie-expire=24h'
      '--cookie-httponly=true'
      '--cookie-domain=app.example.com'
      '--cookie-name=_oauth2_proxy'
      '--cookie-secret=0123456789abcdef'
      '--upstream=http://app:80'
      '--email-domain=ssrf.in'
      '--client-id=<CLIENT_ID>'
      '--client-secret=<CLIENT_SECRET>'

  nginx:
    image: 'nginx:1.13.5'
    links:
      - 'app'
      - 'oauth2-proxy'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    command: 'nginx'
    depends_on:
      - oauth2-proxy
    links:
      - oauth2-proxy

  https-portal:
    image: 'steveltn/https-portal:1'
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'nginx'
    restart: 'always'
    environment:
      DOMAINS: 'app.example.com -> http://nginx'
      STAGE: 'local'
